[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/fci"
  to = "/.netlify/functions/cafci"
  status = 200

[[redirects]]
  from = "/api/cafci/ficha/:fondoId/:claseId"
  to = "https://api.cafci.org.ar/estadisticas/informacion/diaria/ficha/:fondoId/:claseId"
  status = 200

[[redirects]]
  from = "/api/lecaps"
  to = "/.netlify/functions/lecaps"
  status = 200

[[redirects]]
  from = "/api/soberanos"
  to = "/.netlify/functions/soberanos"
  status = 200


[[redirects]]
  from = "/api/mundo"
  to = "/.netlify/functions/mundo"
  status = 200

[[redirects]]
  from = "/api/hot-movers"
  to = "/.netlify/functions/hot-movers"
  status = 200

[[redirects]]
  from = "/api/cotizaciones"
  to = "/.netlify/functions/cotizaciones"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/cer"
  to = "/.netlify/functions/cer"
  status = 200

[[redirects]]
  from = "/api/cer-precios"
  to = "/.netlify/functions/cer-precios"
  status = 200

[[redirects]]
  from = "/api/cer-ultimo"
  to = "/.netlify/functions/cer-ultimo"
  status = 200

[[redirects]]
  from = "/api/ons"
  to = "/.netlify/functions/ons"
  status = 200

[[redirects]]
  from = "/api/hipotecarios"
  to = "/.netlify/functions/hipotecarios"
  status = 200

[[redirects]]
  from = "/api/bcra"
  to = "/.netlify/functions/bcra"
  status = 200

[[redirects]]
  from = "/api/bcra-cambiarias"
  to = "/.netlify/functions/bcra-cambiarias"
  status = 200

[[redirects]]
  from = "/api/dolar"
  to = "/.netlify/functions/dolar"
  status = 200

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/config.json"
  status = 200
