[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/fci"
  to = "/.netlify/functions/cafci"
  status = 200

[[redirects]]
  from = "/api/cafci/ficha/:fondoId/:claseId"
  to = "https://api.cafci.org.ar/estadisticas/informacion/diaria/ficha/:fondoId/:claseId"
  status = 200

[[redirects]]
  from = "/api/lecaps"
  to = "/.netlify/functions/lecaps"
  status = 200

[[redirects]]
  from = "/api/soberanos"
  to = "/.netlify/functions/soberanos"
  status = 200

[[redirects]]
  from = "/api/visits"
  to = "/.netlify/functions/visits"
  status = 200

[[redirects]]
  from = "/api/mundo"
  to = "/.netlify/functions/mundo"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/cer"
  to = "/.netlify/functions/cer"
  status = 200

[[redirects]]
  from = "/api/cer-precios"
  to = "/.netlify/functions/cer-precios"
  status = 200

[[redirects]]
  from = "/api/cer-ultimo"
  to = "/.netlify/functions/cer-ultimo"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/config.json"
  status = 200
